"""Unit tests for IR → full module emission (``SyncAsyncWrapperEmitter.emit_module``)."""

from __future__ import annotations

import re

from synchronicity2.codegen.emitters.sync_async_wrappers import SyncAsyncWrapperEmitter
from synchronicity2.codegen.ir import (
    ClassWrapperIR,
    ManualClassAttributeAccessKind,
    ManualClassAttributeIR,
    ManualReexportIR,
    MethodBindingKind,
    MethodWrapperIR,
    ModuleCompilationIR,
    ModuleImportRefIR,
    ModuleLevelFunctionIR,
    ParameterIR,
)
from synchronicity2.codegen.transformer_ir import (
    AwaitableTypeIR,
    DictTypeIR,
    IdentityTypeIR,
    ImplQualifiedRef,
    ListTypeIR,
    OptionalTypeIR,
    WrapperRef,
)

IMPL = __name__
TARGET = "test_module"

IR_MODULE_TWO_CLASSES = ModuleCompilationIR(
    target_module="test_module",
    synchronizer_name="default_synchronizer",
    impl_modules=frozenset({IMPL}),
    cross_module_imports={},
    typevar_specs=(),
    class_wrappers=(
        ClassWrapperIR(
            impl_ref=ImplQualifiedRef(IMPL, "EmitModuleClassA"),
            wrapper_ref=WrapperRef(TARGET, "EmitModuleClassA"),
            wrapped_bases=(),
            generic_type_parameters=None,
            attributes=(),
            properties=(),
            methods=(
                MethodWrapperIR(
                    method_name="__init__",
                    method_type=MethodBindingKind.INSTANCE,
                    parameters=(
                        ParameterIR(
                            name="value", kind=1, annotation_ir=IdentityTypeIR(signature_text="int"), default_expr=None
                        ),
                    ),
                    is_async_gen=False,
                    is_async=False,
                    return_transformer_ir=IdentityTypeIR(signature_text=""),
                ),
                MethodWrapperIR(
                    method_name="get_value",
                    method_type=MethodBindingKind.INSTANCE,
                    parameters=(),
                    is_async_gen=False,
                    is_async=True,
                    return_transformer_ir=AwaitableTypeIR(inner=IdentityTypeIR(signature_text="int")),
                ),
            ),
        ),
        ClassWrapperIR(
            impl_ref=ImplQualifiedRef(IMPL, "EmitModuleClassB"),
            wrapper_ref=WrapperRef(TARGET, "EmitModuleClassB"),
            wrapped_bases=(),
            generic_type_parameters=None,
            attributes=(),
            properties=(),
            methods=(
                MethodWrapperIR(
                    method_name="__init__",
                    method_type=MethodBindingKind.INSTANCE,
                    parameters=(
                        ParameterIR(
                            name="data",
                            kind=1,
                            annotation_ir=ListTypeIR(item=IdentityTypeIR(signature_text="str")),
                            default_expr=None,
                        ),
                    ),
                    is_async_gen=False,
                    is_async=False,
                    return_transformer_ir=IdentityTypeIR(signature_text=""),
                ),
                MethodWrapperIR(
                    method_name="process_data",
                    method_type=MethodBindingKind.INSTANCE,
                    parameters=(
                        ParameterIR(
                            name="config",
                            kind=1,
                            annotation_ir=DictTypeIR(
                                key=IdentityTypeIR(signature_text="str"), value=IdentityTypeIR(signature_text="int")
                            ),
                            default_expr=None,
                        ),
                        ParameterIR(
                            name="optional_filter",
                            kind=1,
                            annotation_ir=OptionalTypeIR(inner=IdentityTypeIR(signature_text="str")),
                            default_expr="None",
                        ),
                    ),
                    is_async_gen=False,
                    is_async=True,
                    return_transformer_ir=AwaitableTypeIR(inner=ListTypeIR(item=IdentityTypeIR(signature_text="str"))),
                ),
            ),
        ),
    ),
    module_functions_ir=(),
)


def test_emit_module_two_classes_separated_by_blank_lines():
    generated_code = SyncAsyncWrapperEmitter().emit_module(IR_MODULE_TWO_CLASSES)
    compile(generated_code, "<string>", "exec")

    assert generated_code.startswith("# Generated by synchronicity2.\n# This module should not be modified directly.\n")
    class_comment_pattern = r"^# Proxy type for the underlying implementation type .+\.$"
    lines = generated_code.split("\n")
    class_line_indices = [
        i for i, line in enumerate(lines) if line.strip() in {"class EmitModuleClassA:", "class EmitModuleClassB:"}
    ]
    assert len(class_line_indices) >= 2, "Should have at least 2 classes"
    for idx in class_line_indices:
        assert idx > 0
        assert re.match(class_comment_pattern, lines[idx - 1].strip())
    for idx in class_line_indices[1:]:
        prev_line_idx = idx - 2
        assert prev_line_idx >= 0
        assert lines[prev_line_idx].strip() == ""
    assert (
        "_synchronizer.register_wrapper_class(test.unit.compile.test_emit_module.EmitModuleClassA, EmitModuleClassA)"
        in generated_code
    )
    assert (
        "_synchronizer.register_wrapper_class(test.unit.compile.test_emit_module.EmitModuleClassB, EmitModuleClassB)"
        in generated_code
    )
    assert (
        "# Proxy type for the underlying implementation type test.unit.compile.test_emit_module.EmitModuleClassA."
        in generated_code
    )
    assert (
        "# Proxy type for the underlying implementation type test.unit.compile.test_emit_module.EmitModuleClassB."
        in generated_code
    )


def test_emit_module_manual_reexports_and_class_attributes():
    ir = ModuleCompilationIR(
        target_module="test_module",
        synchronizer_name="default_synchronizer",
        impl_modules=frozenset({IMPL}),
        cross_module_imports={},
        typevar_specs=(),
        class_wrappers=(
            ClassWrapperIR(
                impl_ref=ImplQualifiedRef(IMPL, "EmitModuleClassA"),
                wrapper_ref=WrapperRef(TARGET, "EmitModuleClassA"),
                wrapped_bases=(),
                generic_type_parameters=None,
                attributes=(),
                properties=(),
                methods=(
                    MethodWrapperIR(
                        method_name="__init__",
                        method_type=MethodBindingKind.INSTANCE,
                        parameters=(),
                        is_async_gen=False,
                        is_async=False,
                        return_transformer_ir=IdentityTypeIR(signature_text=""),
                    ),
                ),
                manual_attributes=(
                    ManualClassAttributeIR(
                        name="manual_method",
                        access_kind=ManualClassAttributeAccessKind.ATTRIBUTE,
                    ),
                    ManualClassAttributeIR(
                        name="manual_descriptor",
                        access_kind=ManualClassAttributeAccessKind.RAW_CLASS_DICT,
                    ),
                ),
            ),
        ),
        module_functions_ir=(),
        manual_reexports=(
            ManualReexportIR(
                impl_ref=ImplQualifiedRef(IMPL, "forwarded"),
                export_name="forwarded",
            ),
        ),
    )

    generated_code = SyncAsyncWrapperEmitter().emit_module(ir)

    assert "manual_method = test.unit.compile.test_emit_module.EmitModuleClassA.manual_method" in generated_code
    assert (
        "manual_descriptor = test.unit.compile.test_emit_module.EmitModuleClassA.__dict__['manual_descriptor']"
        in generated_code
    )
    assert "forwarded = test.unit.compile.test_emit_module.forwarded" in generated_code


def test_emit_module_imports_default_expression_module_refs():
    ir = ModuleCompilationIR(
        target_module="test_module",
        synchronizer_name="default_synchronizer",
        impl_modules=frozenset({IMPL}),
        cross_module_imports={},
        typevar_specs=(),
        class_wrappers=(),
        module_functions_ir=(
            ModuleLevelFunctionIR(
                impl_ref=ImplQualifiedRef(IMPL, "read_pipe"),
                needs_async_wrapper=False,
                is_async_gen=False,
                parameters=(
                    ParameterIR(
                        name="pipe",
                        kind=1,
                        annotation_ir=IdentityTypeIR(signature_text="int"),
                        default_expr="subprocess.PIPE",
                        default_import_refs=(ModuleImportRefIR(module="subprocess", name="subprocess"),),
                    ),
                ),
                return_transformer_ir=IdentityTypeIR(signature_text="int"),
            ),
        ),
    )

    generated_code = SyncAsyncWrapperEmitter().emit_module(ir)

    assert "import subprocess" in generated_code
    assert "def read_pipe(pipe: int = subprocess.PIPE) -> int:" in generated_code
    assert "from subprocess import PIPE" not in generated_code


def test_emit_module_imports_annotation_module_refs():
    ir = ModuleCompilationIR(
        target_module="test_module",
        synchronizer_name="default_synchronizer",
        impl_modules=frozenset({IMPL}),
        cross_module_imports={},
        typevar_specs=(),
        class_wrappers=(),
        module_functions_ir=(
            ModuleLevelFunctionIR(
                impl_ref=ImplQualifiedRef(IMPL, "round_trip_timestamp"),
                needs_async_wrapper=False,
                is_async_gen=False,
                parameters=(
                    ParameterIR(
                        name="value",
                        kind=1,
                        annotation_ir=IdentityTypeIR(
                            signature_text="datetime.datetime",
                            import_modules=("datetime",),
                        ),
                        default_expr=None,
                    ),
                ),
                return_transformer_ir=IdentityTypeIR(
                    signature_text="datetime.datetime",
                    import_modules=("datetime",),
                ),
            ),
        ),
    )

    generated_code = SyncAsyncWrapperEmitter().emit_module(ir)

    assert "import datetime" in generated_code
    assert "def round_trip_timestamp(value: datetime.datetime) -> datetime.datetime:" in generated_code
