"""Copy the synchronicity *runtime* into a target package for vendoring."""

from __future__ import annotations

import argparse
import keyword
import shutil
import sys
from pathlib import Path

import synchronicity

VENDOR_FILENAMES = ("synchronizer.py", "descriptor.py", "types.py", "module.py")

VENDORED_INIT = '''"""Vendored synchronicity (generated by `synchronicity vendor`).

Includes the runtime used by generated wrappers plus `Module` for implementation modules.
The `synchronicity` CLI / codegen package is still installed separately at build time.
"""

from .descriptor import FunctionWithAio
from .module import DEFAULT_SYNCHRONIZER_NAME, Module
from .synchronizer import Synchronizer, classproperty, get_synchronizer

__all__ = [
    "DEFAULT_SYNCHRONIZER_NAME",
    "FunctionWithAio",
    "Module",
    "Synchronizer",
    "classproperty",
    "get_synchronizer",
]
'''


def validate_runtime_package(name: str) -> None:
    if not name or not name.strip():
        raise ValueError("Package name must be non-empty")
    parts = name.split(".")
    for part in parts:
        if not part.isidentifier():
            raise ValueError(f"Invalid package segment {part!r} in {name!r}")
        if keyword.iskeyword(part):
            raise ValueError(f"Reserved keyword {part!r} cannot be used as a package segment")


def vendor_runtime(*, target_package: str, output_base: Path) -> Path:
    """Write vendored modules under ``output_base`` so they form importable package ``target_package``.

    Returns:
        Path to the leaf package directory (the directory containing ``__init__.py``).
    """
    validate_runtime_package(target_package)
    src_root = Path(synchronicity.__file__).resolve().parent
    parts = target_package.split(".")
    dest_dir = output_base.joinpath(*parts)
    dest_dir.mkdir(parents=True, exist_ok=True)

    # Parent packages (e.g. mylib/ for mylib.synchronicity) must be importable.
    for i in range(1, len(parts)):
        parent_dir = output_base.joinpath(*parts[:i])
        parent_dir.mkdir(parents=True, exist_ok=True)
        parent_init = parent_dir / "__init__.py"
        if not parent_init.exists():
            parent_init.write_bytes(b"")

    for name in VENDOR_FILENAMES:
        src = src_root / name
        if not src.is_file():
            raise FileNotFoundError(f"Missing runtime source file: {src}")
        shutil.copy2(src, dest_dir / name)

    (dest_dir / "__init__.py").write_text(VENDORED_INIT, encoding="utf-8")
    return dest_dir


def run_vendor_cli(argv: list[str] | None = None) -> None:
    parser = argparse.ArgumentParser(
        description="Copy synchronicity runtime and Module into a package tree for vendoring.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Example:
  synchronicity vendor my_lib.synchronicity -o src/

Creates src/my_lib/synchronicity/{{__init__.py,module.py,types.py,descriptor.py,synchronizer.py}}.
Then pass --runtime-package my_lib.synchronicity to ``synchronicity wrappers`` so generated
wrappers import that package instead of top-level synchronicity.
        """,
    )
    parser.add_argument(
        "target_package",
        help="Dotted package path to create under the output directory (e.g. my_lib.synchronicity)",
    )
    parser.add_argument(
        "-o",
        "--output-dir",
        required=True,
        type=Path,
        help="Base directory; package directories are created beneath it",
    )
    args = parser.parse_args(argv)

    try:
        dest = vendor_runtime(target_package=args.target_package, output_base=args.output_dir.resolve())
    except (ValueError, OSError) as e:
        print(f"Error: {e}", file=sys.stderr)
        sys.exit(1)

    print(f"Vendored runtime to {dest}", file=sys.stderr)
