name: Check
on: push

jobs:
  ruff:
    name: Ruff
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - name: Install uv
        uses: astral-sh/setup-uv@caf0cab7a618c569241d31dcd442f54681755d39 # v3
      - name: Install Python
        uses: actions/setup-python@8d9ed9ac5c53483de85588cdf95a591a75ab9f55 # v5
        with:
          python-version: 3.11
      - name: Install dependencies
        run: uv sync --only-group=lint
      - name: Check lint with Ruff
        run: uv run --only-group=lint ruff check .
      - name: Check formatting with Ruff
        run: uv run --only-group=lint ruff format --diff .

  mypy:
    name: MyPy
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - name: Install uv
        uses: astral-sh/setup-uv@caf0cab7a618c569241d31dcd442f54681755d39 # v3
      - name: Install Python
        uses: actions/setup-python@8d9ed9ac5c53483de85588cdf95a591a75ab9f55 # v5
        with:
          python-version: 3.11
      - name: Install dependencies
        run: uv sync --only-group=lint
      - name: Run
        run: uv run --only-group=lint mypy src/synchronicity
